# Generated by Django 4.0.4 on 2022-05-20 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasstation',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='gasstation',
            name='location',
        ),
        migrations.AddField(
            model_name='gasstation',
            name='station_number',
            field=models.SmallIntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='gasstation',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='StationSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_search.fuel')),
                ('gas_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_search.gasstation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='fuel_search.city')),
            ],
            options={
                'unique_together': {('location', 'fuel_t')},
            },
        ),
    ]
