# Generated by Django 4.0.4 on 2022-05-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_search', '0002_remove_gasstation_fuel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasstation',
            name='fuel_type',
            field=models.ManyToManyField(related_name='fuel_types', through='fuel_search.StationSupply', to='fuel_search.fuel'),
        ),
    ]
