# Generated by Django 4.0.4 on 2022-05-22 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_search', '0003_gasstation_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationsupply',
            name='gas_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station', to='fuel_search.gasstation'),
        ),
    ]
