# Generated by Django 4.0.4 on 2022-05-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_search', '0004_alter_stationsupply_gas_station'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationsupply',
            options={'ordering': ('location__city_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='stationsupply',
            unique_together={('location', 'fuel_t', 'gas_station')},
        ),
    ]
