# Generated by Django 4.0.4 on 2022-05-31 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_search', '0008_alter_city_options_alter_fuel_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StationSupply',
            new_name='Supply',
        ),
        migrations.RenameField(
            model_name='gasstation',
            old_name='location',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='gasstation',
            old_name='fuel_types',
            new_name='supply',
        ),
    ]
