# Generated by Django 4.0.5 on 2022-06-01 17:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_search', '0009_supply_rename_location_gasstation_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuel',
            options={},
        ),
        migrations.RenameField(
            model_name='fuel',
            old_name='type',
            new_name='type_fuel',
        ),
        migrations.RenameField(
            model_name='gasstation',
            old_name='supply',
            new_name='fuels',
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='created',
        ),
        migrations.AddField(
            model_name='fuel',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gasstation',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='fuel_search.city'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuel_search.fuel'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='gas_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='fuel_search.gasstation'),
        ),
    ]
