# Generated by Django 4.0.4 on 2022-06-06 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_search', '0009_supply_rename_location_gasstation_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasstation',
            name='supply',
        ),
        migrations.AddField(
            model_name='gasstation',
            name='fuels',
            field=models.ManyToManyField(related_name='fuel_types', through='fuel_search.Supply', to='fuel_search.fuel'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gasstation',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='fuel_search.city'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_on_station', to='fuel_search.fuel'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='gas_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='fuel_search.gasstation'),
        ),
    ]
